
import * as React from 'react';
import Urunler from "../../components/pages_yeni/Urunler"
import LoadingComponent from "../../components/pages_yeni/loading"
import Container from "@mui/material/Container";
import HeaderKategori from "../../components/pages_yeni/header/HeaderKategori";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import axios from "axios";
import MusteriBildirim from "../../components/pages_yeni/MusteriBildirim";
import SurenizDoldu from "../../components/pages_yeni/SurenizDoldu";
import Scroll from "react-scroll";
import Whatsapp from "../../components/pages_yeni/Whatsapp";
import Dil from "../../components/pages_yeni/Dil";
import SimpleDialogDemo from "../../components/Dialog/dialog1";

const PagesYeni = () => {

    const router = useRouter();
    const { query } = useRouter();
    const [value, setValue] = React.useState(0);
    const [kategori, setKategori] = React.useState([]);
    const [kalanGun, setKalanGun] = useState(1)

    const [isLoading, setIsLoading] = useState(true)
    const [firma, setFirma] = React.useState([]);
    const [dialogOpen, setDialogOpen] = React.useState(false);
    const [seciliDil, setSeciliDil] = useState("tr")
    const headers = {
        "Content-Type": "application/json"
    };

    useEffect(() => {
        const dilKontrol = sessionStorage.getItem("dil")
        if (dilKontrol == null) {
            setDialogOpen(true)
        } else {
            setSeciliDil(dilKontrol)
        }
    }, [])

    useEffect(() => {

        const cardList = {};
        const fetchPost = async () => {
            if (query.restoran) {
                let response = await axios.post(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/urunGetir`, {
                    kategori_id: query.kategori_id,
                    restoran: query.restoran
                }, { headers }).then(res => {
                    setKategori(res.data.kategoriler)
                    setFirma(res.data.firma)
                    let date1 = new Date()
                    let date2 = new Date(res.data.firma.hizmetBitisTarihi)
                    setKalanGun(Math.floor((date2 - date1) / (1000 * 3600 * 24)))
                    setIsLoading(false);
                });

            }
        };
        fetchPost()
    }, [query.restoran]);

    useEffect(() => {
        setTimeout(() => {
            var scroller = Scroll.scroller;
            scroller.scrollTo(query.kategori_id, {
                duration: 1500,
                delay: 100,
                smooth: true,
                offset: -170,
            })
        }, 1000);

    }, [query.kategori_id])
    return (
        <>

            {isLoading &&
                <>
                    <LoadingComponent firma={firma} />
                </>
            }
            {!isLoading &&
                <>

                    {kalanGun <= 0 &&
                        <SurenizDoldu firma={firma}></SurenizDoldu>
                    }

                    {kalanGun > 0 &&
                        <>
                            <Head>
                                <title>Hanipop Qr Menü</title>
                                <meta name="description" content="Generated by create next app" />
                                <meta name="viewport" content="width=device-width, initial-scale=1" />
                            </Head>
                            <main>
                                <Container sx={{ marginTop: 8 }}>
                                    <HeaderKategori seciliDil={seciliDil} setSeciliDil={setSeciliDil} firma={firma} kategori={kategori}></HeaderKategori>

                                    <SimpleDialogDemo firma={firma} seciliDil={seciliDil} setSeciliDil={setSeciliDil} title={"Dil Seçiniz"} dialogOpen={dialogOpen} setDialogOpen={setDialogOpen}></SimpleDialogDemo>
                                    <Urunler seciliDil={seciliDil} setSeciliDil={setSeciliDil} firma={firma} kategori={kategori} firma={firma}></Urunler>

                                    {query.restoran == "kodlooper-cafe" &&
                                        <Whatsapp firma={firma}></Whatsapp>
                                    }
                                    <MusteriBildirim firma={firma}></MusteriBildirim>
                                    <Dil setDialogOpen={setDialogOpen} firma={firma}></Dil>
                                </Container>
                            </main>
                        </>
                    }

                </>
            }

        </>
    )
}

export default PagesYeni;
