import * as React from 'react';
import Urunler from "../../../components/pages_yeni/Urunler"
import Container from "@mui/material/Container";
import HeaderKategori from "../../../components/pages_yeni/header/HeaderKategori";
import Head from "next/head";
import Typography from "@mui/material/Typography";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import axios from "axios";
import Grid from "@mui/material/Grid";
import Card from "@mui/material/Card";
import CardMedia from "@mui/material/CardMedia";
import CardContent from "@mui/material/CardContent";
import LoadingComponent from "../../../components/pages_yeni/loading";

const PagesYeni = () => {

    const router = useRouter();
    const { query } = useRouter();
    const [isLoading, setIsLoading] = useState(true)
    const [value, setValue] = React.useState(0);

    const [kategori, setKategori] = React.useState([]);
    const [bizdenkareler, setBizdenkareler] = React.useState([]);


    const [firma, setFirma] = React.useState([]);
    const headers = {
        "Content-Type": "application/json"
    };
    useEffect(() => {

        const cardList = {};
        const fetchPost = async () => {

            if (query.restoran) {
                let response = await axios.post(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/urunGetir`, {
                    kategori_id: query.kategori_id,
                    restoran: query.restoran
                }, { headers }).then(res => {

                    setKategori(res.data.kategoriler)
                    setFirma(res.data.firma)
                    setBizdenkareler(res.data.firma.bizden_kareler)
                    setIsLoading(false);
                });
            } else {

                /*let response = await axios.post(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/urunGetir`,{
                    kategori_id:"11"
                }, { headers }).then(res=>{
                    setData(res.data)
                });*/
            }

        };
        fetchPost();
    }, [query.restoran]);
    return (
        <>

            {isLoading &&
                <>
                    <LoadingComponent firma={firma} />
                </>
            }

            {!isLoading &&
                <>
                    <Head>
                        <title>Hanipop Qr Menü</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                    </Head>
                    <main>
                        <Container sx={{ marginTop: 8 }}>
                            <HeaderKategori firma={firma} kategori={kategori} temaUrl={"tema2"}></HeaderKategori>
                            <Typography sx={{ marginTop: 9 }} variant="h4" gutterBottom>
                                Bizden Kareler
                            </Typography>

                            <Grid container spacing={2}>
                                {bizdenkareler.map(res => {
                                    return (
                                        <Grid item height={400} xs={12} md={4}>
                                            <Card sx={{ maxWidth: 445, margin: 2 }}>
                                                <CardMedia
                                                    sx={{ height: 240 }}
                                                    image={"https://menu.hanipop.com/" + res.bizden_kareler_gorsel}
                                                    title={res.sube_adi}
                                                />

                                            </Card>
                                        </Grid>
                                    )

                                })}
                            </Grid>
                        </Container>
                    </main>
                </>
            }

        </>
    )
}

export default PagesYeni;
