
import * as React from 'react';
import Urunler  from "../../components/pages_yeni/Urunler"
import Container from "@mui/material/Container";
import HeaderKategori from "../../components/pages_yeni/header/HeaderKategori";
import Head from "next/head";
import Typography from "@mui/material/Typography";
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import axios from "axios";
import LoadingComponent from "../../components/pages_yeni/loading";

const PagesYeni = () => {

    const [isLoading, setIsLoading] = useState(true)
    const router = useRouter();
    const { query } = useRouter();

    const [value, setValue] = React.useState(0);

    const [kategori, setKategori] = React.useState([]);


    const [firma, setFirma] = React.useState([]);
    const headers = {
        "Content-Type": "application/json"
    };
    useEffect(() => {

        const cardList = {};
        const fetchPost = async () => {

            if(query.restoran)
            {
                let response = await axios.post(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/urunGetir`,{
                    kategori_id:query.kategori_id,
                    restoran:query.restoran
                }, { headers }).then(res=>{

                    setKategori(res.data.kategoriler)
                    setFirma(res.data.firma)

                    setIsLoading(false);
                });
            }else{

                /*let response = await axios.post(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/urunGetir`,{
                    kategori_id:"11"
                }, { headers }).then(res=>{
                    setData(res.data)
                });*/
            }

        };
        fetchPost();
    }, [query.restoran]);
    return (
        <>


            {isLoading &&
                <>
                    <LoadingComponent firma={firma}/>
                </>
            }


            {!isLoading &&
                <>
                    <Head>
                        <title>Hanipop Qr Menü</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                    </Head>
                    <main>
                        <Container sx={{marginTop:8}}>
                            <HeaderKategori firma={firma} kategori={kategori}></HeaderKategori>
                            <Typography  sx={{marginTop:9}} variant="h4" gutterBottom>
                                Misyonumuz
                            </Typography>

                            <Typography variant="body2" gutterBottom
                                        dangerouslySetInnerHTML={{__html: firma.misyonumuz}} />
                        </Container>
                    </main>
                </>
            }

        </>
    )
}

export default PagesYeni;